### ISSUE TITLE
Disabled SplitButton.Button's should not fire onClick

### ISSUE THREAD

**Issue by jondlm** [appnexus/lucid#732] opened 2017-03-06 15:33 UTC
`SplittButton.Button`s are incorrectly firing `onClick` when they are `isDisabled`.

[Repro codepen](http://codepen.io/jondlm/pen/yMOMOy?editors=0111)

**Comment by mute** [comment] 2017-03-06 17:15
I think this is a duplicate of https://github.com/appnexus/lucid/issues/729

**Closed** 2017-03-06 17:23 UTC
Labels: bug, help wanted
