### ISSUE TITLE
Portal element of a DropMenu is not unmounted from the DOM when the menu element is closed

### ISSUE THREAD

**Issue by slaude** [appnexus/lucid#494] opened 2016-09-01 16:21 UTC
See screencast here: http://screencast.com/t/qVrEjhqLBU

**Comment by ogupte** [comment] 2016-09-01 16:44
Duplicate of #421

**Comment by jondlm** [comment] 2016-09-01 20:41
Doesn't actually appear to be a duplicate. We'll look into it.

**Comment by jacklenehan** [comment] 2017-01-31 21:36
Joe investigated, can't repro.

**Comment by ogupte** [comment] 2018-02-13 21:52
i just confirmed that the leak happens on the react global reference, not on the DOM, the dom element gets cleaned up, but the component never unmounts. calling `ReactDom.unmountComponentAtNode(this.portalElement);` before the DOM cleanup should fix this.

**Closed** 2018-02-14 00:11 UTC
Labels: bug
